### ISSUE TITLE
No module named 'jax.api'

### ISSUE THREAD

**Issue by Anson-He** [lafeat/apbench#2]
How to solve No module named 'jax.api'?

**Comment by Anson-He** [comment]
I solved this problem by replaceing 'from jax.api' with 'from jax' simply, the same as 'from jax.config' etc.

**Comment by Tianyue818** [comment]
Hi, 

Due to version issues with the JAX package, the sub-modules of NTGA poisons may encounter some problems. Therefore, we suggest using the CIFAR-10 NTGA poisons provided by the [NTGA](https://github.com/lionelmessi6410/ntga), despite the differences in dataset size and type. I hope this reply is helpful to you.
